version: '3.8'
services:
  web:
      image: nginx:latest
      ports:
          - "8086:80"
      volumes:
          - ./:/var/www/html:delegated
          - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      build: 
            context: ./docker/php
            dockerfile: Dockerfile
      volumes:
          - ./:/var/www/html:delegated

